/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 frontend/public/Generate_a_3d_Wallet__1119102127_refine.glb -t -r public 
*/

import { useGLTF } from '@react-three/drei'
import React from 'react'
import type * as THREE from 'three'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh;
  };
  materials: {};
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/../frontend/public/Generate_a_3d_Wallet__1119102127_refine.glb',
  ) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload(
  '/../frontend/public/Generate_a_3d_Wallet__1119102127_refine.glb',
)
